### ISSUE TITLE
issues #1

### ISSUE THREAD

**Issue by jonaswolf** [LBBO/CodeHighlighter#1]
Hallo @lbbo,

maybe, u should describe the application a bit more specific, that would be nice, I think not every person understand, what do you would like to say with the sentence highliting...

I'll tell u more via Telegram, or twitter

**Comment by jonaswolf** [comment]
pleas also link xenux (xenux.bplaxed.net or https://github.com/sveneberth/xenux) ;)

That would make @sveneberth very happy

**Comment by LBBO** [comment]
Both were done already but I improved both. Links to XENUX are now found in the README file and above the actual code in the example.html. The library is described in the README file as well.

**Comment by jonaswolf** [comment]
I'm very proud of you!
